package example.model;

public class Books {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.title
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.authorId
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    private Integer authorid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.title
     *
     * @return the value of books.title
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.title
     *
     * @param title the value for books.title
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.authorId
     *
     * @return the value of books.authorId
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.authorId
     *
     * @param authorid the value for books.authorId
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }
}