package example.model;

public class GuestbookMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestbook_message.message_id
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestbook_message.guest_name
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    private String guestName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestbook_message.password
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestbook_message.message
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook_message.message_id
     *
     * @return the value of guestbook_message.message_id
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook_message.message_id
     *
     * @param messageId the value for guestbook_message.message_id
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook_message.guest_name
     *
     * @return the value of guestbook_message.guest_name
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public String getGuestName() {
        return guestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook_message.guest_name
     *
     * @param guestName the value for guestbook_message.guest_name
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook_message.password
     *
     * @return the value of guestbook_message.password
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook_message.password
     *
     * @param password the value for guestbook_message.password
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook_message.message
     *
     * @return the value of guestbook_message.message
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook_message.message
     *
     * @param message the value for guestbook_message.message
     *
     * @mbg.generated Fri Mar 22 15:58:37 KST 2024
     */
    public void setMessage(String message) {
        this.message = message;
    }
}